version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${BACKEND_URL}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongo_db
    volumes:
      - ./Uploads:/Uploads

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  
